package com.tegonal.variist.generators

import com.tegonal.variist.config.VariistConfig
import com.tegonal.variist.utils.createVariistRandom

/**
 * Represents an [ArgsGenerator] which provides [generate] which generates [T]s an infinite number of times in a random
 * or not defined order.
 *
 * @param T the type of values generated by `this` [ArbArgsGenerator].
 *
 * @since 2.0.0
 */
// TODO 3.1.0 introduce something like ArbArgsSizeAwareGenerator which has a size and
//  provides a way to turn itself into an OrderedArgsGenerator. This would be useful for small spaces as we could just
//  return all values in case an ArgsRangeDecider decides to take more then the available size
interface ArbArgsGenerator<out T> : ArgsGenerator<T> {

	/**
	 * Maps the values `this` [ArbArgsGenerator] generates to type [R] with the help of the given [transform] function.
	 *
	 * @param transform The transformation function which takes a [T] and produces an [R].
	 *
	 * @param R the type of values generated by the resulting [ArbArgsGenerator].
	 *
	 * @return The resulting [ArbArgsGenerator] which generates values of type [R].
	 *
	 * @since 2.0.0
	 */
	override fun <R> map(transform: (T) -> R): ArbArgsGenerator<R> =
		transform { seq -> seq.map(transform) }

	/**
	 * Returns one random value of type [T].
	 *
	 * @since 2.0.0
	 */
	fun generateOne(seedOffset: Int = 0): T {
		// we don't use first as it checks hasNext in addition and we know that it has to have one as the
		// Sequence needs to be infinite according to the ArgsGenerator contract
		return generate(seedOffset).iterator().next()
	}

	/**
	 * Generates an infinite stream of random values of type [T].
	 *
	 * @param seedOffset an offset to [VariistConfig.seed] which shall be applied in
	 *   case this [ArbArgsGenerator] relies on [createVariistRandom].
	 * @since 2.0.0
	 */
	fun generate(seedOffset: Int = 0): Sequence<T>
}
