package com.tegonal.variist.generators

import com.tegonal.variist.generators.impl.ArbArgsGeneratorAsSemiOrderedGenerator

/**
 * Turns `this` [ArbArgsGenerator] into a [SemiOrderedArgsGenerator] with size 1.
 *
 * With `size = 1` because the constant part of this generator is that it yields always values
 * from the same [ArbArgsGenerator].
 *
 * @param A1 The type of values generated by `this` [ArbArgsGenerator].
 * @return The resulting [SemiOrderedArgsGenerator].
 *
 * @since 2.3.0
 */
fun <A1> ArbArgsGenerator<A1>.toSemiOrdered() = ArbArgsGeneratorAsSemiOrderedGenerator(this)
