package com.tegonal.variist.generators

import com.tegonal.variist.config.IsComponentFactoryContainerProvider

/**
 * Represents a generator which generates [T]s.
 *
 * @param T the type of values generated by `this` [ArgsGenerator].
 *
 * @since 2.0.0
 */
interface ArgsGenerator<out T> : IsComponentFactoryContainerProvider {

	/**
	 * Maps the values `this` [ArgsGenerator] generates to type [R] with the help of the given [transform] function.
	 *
	 * @param transform The transformation function which takes a [T] and produces an [R].
	 *
	 * @param R the type of values generated by the resulting [ArgsGenerator].
	 *
	 * @return The resulting [ArgsGenerator] which generates values of type [R].
	 *
	 * @since 3.0.0
	 */
	fun <R> map(transform: (T) -> R): ArgsGenerator<R>
}
