//TODO 3.0.0 rename file to semiOrderedLike...
package com.tegonal.variist.generators

import com.tegonal.variist.generators.impl.SemiOrderedArgsGeneratorConcatenator

/**
 * Concatenates all given [SemiOrderedLikeArgsGenerator] resulting in an [SemiOrderedArgsGenerator] which yields
 * the values of the first [SemiOrderedLikeArgsGenerator], then the second generator ... up to the values of
 * the last generator and then starting over.
 *
 * I.e. the resulting [SemiOrderedArgsGenerator] generates the sum of [SemiOrderedLikeArgsGenerator.size] values
 * before repeating.
 *
 * @param T The type of values generated by the [SemiOrderedLikeArgsGenerator]s.
 *
 * @return The resulting [SemiOrderedArgsGenerator] after concatenation.
 *
 * @since 3.0.0
 */
fun <T> Sequence<SemiOrderedLikeArgsGenerator<T>>.concatAll(): SemiOrderedLikeArgsGenerator<T> = concatAll(iterator())

/**
 * Concatenates all given [SemiOrderedLikeArgsGenerator] resulting in an [SemiOrderedArgsGenerator] which yields
 * the values of the first [SemiOrderedArgsGenerator], then the second generator ... up to the values of
 * the last generator and then starting over.
 *
 * I.e. the resulting [SemiOrderedArgsGenerator] generates the sum of [SemiOrderedArgsGenerator.size] values
 * before repeating.
 *
 * @param T The type of values generated by the [SemiOrderedLikeArgsGenerator]s.
 *
 * @return The resulting [SemiOrderedArgsGenerator] after concatenation.
 *
 * @since 3.0.0
 */
fun <T> Iterable<SemiOrderedLikeArgsGenerator<T>>.concatAll(): SemiOrderedLikeArgsGenerator<T> = concatAll(iterator())


/**
 * Concatenates all given [SemiOrderedArgsGenerator] resulting in an [SemiOrderedArgsGenerator] which yields
 * the values of the first [SemiOrderedArgsGenerator], then the second generator ... up to the values of
 * the last generator and then starting over.
 *
 * I.e. the resulting [SemiOrderedArgsGenerator] generates the sum of [SemiOrderedArgsGenerator.size] values before repeating.
 *
 * @param T The type of values generated by the [SemiOrderedArgsGenerator]s.
 *
 * @return The resulting [SemiOrderedArgsGenerator] after concatenation.
 *
 * @since 2.0.0
 */
fun <T> Sequence<SemiOrderedArgsGenerator<T>>.concatAll(): SemiOrderedArgsGenerator<T> {
	// we know that we use SemiOrderedArgsGeneratorConcatenator which is a SemiOrderedArgsGenerator. I.e. as soon as we
	// have 2 or more generators in the Sequence we can be sure we deal with a SemiOrderedArgsGenerator.
	// Since we know that also the first generator in the Sequence has to be a SemiOrderedArgsGenerator we can be
	// sure it the resulting is a SemiOrderedArgsGenerator as well.
	return concatAll(iterator()) as SemiOrderedArgsGenerator<T>
}

/**
 * Concatenates all given [SemiOrderedArgsGenerator] resulting in an [SemiOrderedArgsGenerator] which yields
 * the values of the first [SemiOrderedArgsGenerator], then the second generator ... up to the values of
 * the last generator and then starting over.
 *
 * I.e. the resulting [SemiOrderedArgsGenerator] generates the sum of [SemiOrderedArgsGenerator.size] values before repeating.
 *
 * @param T The type of values generated by the [SemiOrderedArgsGenerator]s.
 *
 * @return The resulting [SemiOrderedArgsGenerator] after concatenation.
 *
 * @since 2.0.0
 */
fun <T> Iterable<SemiOrderedArgsGenerator<T>>.concatAll(): SemiOrderedArgsGenerator<T> {
	// we know that we use SemiOrderedArgsGeneratorConcatenator which is a SemiOrderedArgsGenerator. I.e. as soon as we
	// have 2 or more generators in the Sequence we can be sure we deal with a SemiOrderedArgsGenerator.
	// Since we know that also the first generator in the Sequence has to be a SemiOrderedArgsGenerator we can be
	// sure it the resulting is a SemiOrderedArgsGenerator as well.
	return concatAll(iterator()) as SemiOrderedArgsGenerator<T>
}

private fun <T> concatAll(iterator: Iterator<SemiOrderedLikeArgsGenerator<T>>): SemiOrderedLikeArgsGenerator<T> {
	check(iterator.hasNext()) { "cannot concatenate an empty Iterator of SemiOrderedLikeArgsGenerator" }
	val first = iterator.next()
	var result = first
	while (iterator.hasNext()) {
		//TODO 3.5.0 would it be worth to introduce a Concatenator which takes n SemiOrderedArgsGenerator instead of just 2?
		result += iterator.next()
	}
	return result
}

/**
 * Merges `this` [SemiOrderedLikeArgsGenerator] with the given [other]&nbsp;[SemiOrderedLikeArgsGenerator] resulting in an
 * [SemiOrderedArgsGenerator] which yields the values of `this` [SemiOrderedLikeArgsGenerator] and then of the [other]
 * before repeating.
 *
 * The resulting [SemiOrderedArgsGenerator] generates
 * [this.size][SemiOrderedLikeArgsGenerator.size] + [other.size][SemiOrderedLikeArgsGenerator.size] values before repeating.
 *
 * @param other The other [SemiOrderedLikeArgsGenerator].
 * @param T The type of values generated by `this` and [other] [SemiOrderedArgsGenerator]s.
 *
 * @return The resulting [SemiOrderedArgsGenerator] after concatenation.
 *
 * @since 2.0.0
 */
operator fun <T> SemiOrderedLikeArgsGenerator<T>.plus(
	other: SemiOrderedLikeArgsGenerator<T>,
): SemiOrderedArgsGenerator<T> = SemiOrderedArgsGeneratorConcatenator(this, other)
