package com.tegonal.variist.generators

/**
 * Concatenates all given [SemiOrderedArgsGenerator] resulting in an [SemiOrderedArgsGenerator] which yields
 * the values of the first [SemiOrderedArgsGenerator], then the second generator ... up to the values of
 * the last generator and then starting over.
 *
 * I.e. the resulting [SemiOrderedArgsGenerator] generates the sum of [SemiOrderedArgsGenerator.size] values before repeating.
 *
 * @param T The type of values generated by the [SemiOrderedArgsGenerator]s.
 *
 * @return The resulting [SemiOrderedArgsGenerator] after concatenation.
 *
 * @since 2.0.0
 */
fun <T> Sequence<SemiOrderedArgsGenerator<T>>.concatAll(): SemiOrderedArgsGenerator<T> {
	// we know that we use SemiOrderedArgsGeneratorConcatenator which is a SemiOrderedArgsGenerator. I.e. as soon as we
	// have 2 or more generators in the Sequence we can be sure we deal with a SemiOrderedArgsGenerator.
	// Since we know that also the first generator in the Sequence has to be a SemiOrderedArgsGenerator we can be
	// sure the resulting generator is a SemiOrderedArgsGenerator as well.
	return (this as Sequence<SemiOrderedLikeArgsGenerator<T>>).concatAll() as SemiOrderedArgsGenerator<T>
}

/**
 * Concatenates all given [SemiOrderedArgsGenerator] resulting in an [SemiOrderedArgsGenerator] which yields
 * the values of the first [SemiOrderedArgsGenerator], then the second generator ... up to the values of
 * the last generator and then starting over.
 *
 * I.e. the resulting [SemiOrderedArgsGenerator] generates the sum of [SemiOrderedArgsGenerator.size] values before repeating.
 *
 * @param T The type of values generated by the [SemiOrderedArgsGenerator]s.
 *
 * @return The resulting [SemiOrderedArgsGenerator] after concatenation.
 *
 * @since 2.0.0
 */
fun <T> Iterable<SemiOrderedArgsGenerator<T>>.concatAll(): SemiOrderedArgsGenerator<T> {
	// we know that we use SemiOrderedArgsGeneratorConcatenator which is a SemiOrderedArgsGenerator. I.e. as soon as we
	// have 2 or more generators in the Sequence we can be sure we deal with a SemiOrderedArgsGenerator.
	// Since we know that also the first generator in the Sequence has to be a SemiOrderedArgsGenerator we can be
	// sure the resulting generator is a SemiOrderedArgsGenerator as well.
	return (this as Iterable<SemiOrderedLikeArgsGenerator<T>>).concatAll() as SemiOrderedArgsGenerator<T>
}
