package com.tegonal.variist.generators

//TODO 2.3.0 check if it would be worth to introduce SemiOrderedArgsGeneratorLike. I already figured that making
// Ordered a subtype of SemiOrdered is wrong and we can see now with generateOne requiring a seedOffset for SemiOrdered
// but never for Ordered that it was indeed not that nice. Maybe something we can neglect due to the benefit of sharing
// the same logic for SemiOrderedArgsGenerator and OrderedArgsGenerator but in the same time every extension one defines
// for SemiOrderedArgsGenerator is automatically available for Ordered as well which is again not that nice.

/**
 * Represents an [ArgsGenerator] which provides the method [generate] where some part of [T] is always in the
 * same order and a finite number before repeating and another part of [T] is undefined (could be ordered and finite,
 * could be ordered and infinite, could be random).
 *
 * @param T the type of values generated by `this` [ArbArgsGenerator].
 *
 * @since 2.0.0
 */
interface SemiOrderedArgsGenerator<out T> : ArgsGenerator<T> {
	/**
	 * Returns the maximum of values `this` generator is able to generate before some part of it start over again.
	 */
	val size: Int

	/**
	 * Returns the value at the given [offset] requesting to pass the given [seedOffset] to
	 * composed [ArbArgsGenerator]s.
	 */
	fun generateOne(offset: Int, seedOffset: Int = 0): T {
		// we don't use first as it checks hasNext in addition and we know that it has to have one as the
		// Sequence needs to be infinite according to the ArgsGenerator contract
		return generate(offset, seedOffset).iterator().next()
	}

	/**
	 * Returns an infinite [Sequence] of values starting at [offset] -- requesting to pass the given [seedOffset] to
	 * composed [ArbArgsGenerator]s -- and repeating after reaching [size] of values where one part/aspect of
	 * this generator is always the same when generated multiple times.
	 */
	fun generate(offset: Int, seedOffset: Int = 0): Sequence<T>
}
