//TODO 3.0.0 rename file to semiOrderedLike...
package com.tegonal.variist.generators

import com.tegonal.variist.config._components
import com.tegonal.variist.generators.impl.IntFromUntilArbArgsGenerator

/**
 * Turns `this` [SemiOrderedLikeArgsGenerator] into an [ArbArgsGenerator].
 *
 * @param T The type of values generated by `this` [SemiOrderedLikeArgsGenerator].
 *
 * @return The resulting [ArbArgsGenerator].
 *
 * @since 2.0.0
 */
fun <T> SemiOrderedLikeArgsGenerator<T>.toArbArgsGenerator(): ArbArgsGenerator<T> =
	IntFromUntilArbArgsGenerator(_components, from = 0, toExclusive = size)
		.map { offset -> this.generateOne(offset) }
