package com.tegonal.variist.generators

import com.tegonal.variist.config.ComponentFactoryContainerProvider
import com.tegonal.variist.generators.impl.DefaultArbExtensionPoint
import com.tegonal.variist.generators.impl.DefaultOrderedExtensionPoint
import com.tegonal.variist.generators.impl.DefaultSemiOrderedExtensionPoint

//TODO 2.3.0 check if it would be worth to introduce SemiOrderedArgsGeneratorLike. I already figured that making
// Ordered a subtype of SemiOrdered is wrong and we can see now with generateOne requiring a seedOffset for SemiOrdered
// but never for Ordered that it was indeed not that nice. Maybe something we can neglect due to the benefit of sharing
// the same logic for SemiOrderedArgsGenerator and OrderedArgsGenerator but in the same time every extension one defines
// for SemiOrderedArgsGenerator is automatically available for Ordered as well which is again not that nice.

/**
 * Represents an [ArgsGenerator] which provides the method [generate] where some part of [T] is always in the
 * same order and a finite number before repeating and another part of [T] is undefined (could be ordered and finite,
 * could be ordered and infinite, could be random).
 *
 * @param T the type of values generated by `this` [ArbArgsGenerator].
 *
 * @since 2.0.0
 */
interface SemiOrderedArgsGenerator<out T> : ArgsGenerator<T> {
	/**
	 * Returns the maximum of values `this` generator is able to generate before some part of it start over again.
	 */
	val size: Int

	/**
	 * Returns the value at the given [offset].
	 */
	fun generateOne(offset: Int): T {
		// we don't use first as it checks hasNext in addition and we know that it has to have one as the
		// Sequence needs to be infinite according to the ArgsGenerator contract
		return generate(offset).iterator().next()
	}

	/**
	 * Returns an infinite [Sequence] of values starting at [offset] and repeating after reaching [size] of values
	 * where one part/aspect of this generator is always the same when generated multiple times.
	 */
	fun generate(offset: Int): Sequence<T>
}

/**
 * Represents an interface each [SemiOrderedArgsGenerator] must implement which provides additional core functionality
 * which is relevant for users which create own [SemiOrderedArgsGenerator]s or combiner functions.
 *
 * The separation between [SemiOrderedArgsGenerator] and [CoreSemiOrderedArgsGenerator] makes sure the API stays clean
 * for regular users which just use [ordered]/[semiOrdered] but don't define own
 * [SemiOrderedArgsGenerator] implementations.
 *
 * @since 2.3.0
 */
interface CoreSemiOrderedArgsGenerator<out T> : SemiOrderedArgsGenerator<T>, ComponentFactoryContainerProvider {

	/**
	 * Returns the value at the given [offset] passing the given [seedOffset] to composed [ArbArgsGenerator]s.
	 */
	fun generateOne(offset: Int, seedOffset: Int): T {
		// we don't use first as it checks hasNext in addition and we know that it has to have one as the
		// Sequence needs to be infinite, according to the ArgsGenerator contract
		return generate(offset, seedOffset).iterator().next()
	}

	/**
	 * Returns an infinite [Sequence] of values starting at [offset] and repeating after reaching [size] of values
	 * where one part/aspect of this generator is always the same when generated multiple times.
	 */
	fun generate(offset: Int, seedOffset: Int): Sequence<T>
}

/**
 * Creates an [ArbExtensionPoint] based on `this` [CoreSemiOrderedArgsGenerator].
 *
 * @since 2.3.0
 */
val <T> CoreSemiOrderedArgsGenerator<T>.arb: ArbExtensionPoint
	get() = DefaultArbExtensionPoint(componentFactoryContainer)

/**
 * Creates an [SemiOrderedExtensionPoint] based on `this` [CoreSemiOrderedArgsGenerator].
 *
 * @since 2.3.0
 */
val <T> CoreSemiOrderedArgsGenerator<T>.semiOrdered: SemiOrderedExtensionPoint
	get() = DefaultSemiOrderedExtensionPoint(componentFactoryContainer)

/**
 * Creates an [OrderedExtensionPoint] based on `this` [CoreSemiOrderedArgsGenerator].
 *
 * @since 2.3.0
 */
val <T> CoreSemiOrderedArgsGenerator<T>.ordered: OrderedExtensionPoint
	get() = DefaultOrderedExtensionPoint(componentFactoryContainer)

/**
 * Casts `this` to a [CoreArbArgsGenerator].
 *
 * @since 2.0.0
 */
@Suppress("ObjectPropertyName")
val <T> SemiOrderedArgsGenerator<T>._core: CoreSemiOrderedArgsGenerator<T>
	get() = when (this) {
		is CoreSemiOrderedArgsGenerator<T> -> this
		else -> error("The ${SemiOrderedArgsGenerator::class.simpleName} ${this::class.qualifiedName} does not implement ${CoreSemiOrderedArgsGenerator::class.qualifiedName}, please inform the author.")
	}
