@file:JvmName("SemiOrderedLikeCartesianKt")
@file:JvmMultifileClass

package com.tegonal.variist.generators

import com.tegonal.variist.generators.impl.SemiOrderedCartesianProductArgsGenerator

/**
 * Combines `this` [SemiOrderedLikeArgsGenerator] with the given [other]&nbsp;[SemiOrderedLikeArgsGenerator] resulting
 * in their Cartesian product where the values are [transform]ed into values of type [R].
 *
 * The resulting [SemiOrderedArgsGenerator] generates
 * [this.size][SemiOrderedArgsGenerator.size] * [other.size][SemiOrderedArgsGenerator.size] values before repeating.
 *
 * @param other The other [SemiOrderedLikeArgsGenerator] which generates values of type [A2].
 * @param A1 The type of values generated by `this` [SemiOrderedLikeArgsGenerator].
 * @param A2 the type of values generated by the [other]&nbsp;[SemiOrderedLikeArgsGenerator].
 * @param R the type of values generated by the resulting [SemiOrderedArgsGenerator].
 *
 * @return The resulting [SemiOrderedArgsGenerator] which represents the Cartesian product and generates values of type [R].
 *
 * @since 2.0.0
 */
fun <A1, A2, R> SemiOrderedLikeArgsGenerator<A1>.cartesian(
	other: SemiOrderedLikeArgsGenerator<A2>,
	transform: (A1, A2) -> R
): SemiOrderedArgsGenerator<R> = SemiOrderedCartesianProductArgsGenerator(this, other, transform)
