package com.tegonal.variist.generators

import com.tegonal.variist.generators.impl.InternalDangerousApi
import com.tegonal.variist.generators.impl.transformInternal

/**
 * Represents a [SemiOrderedLikeArgsGenerator] where some part/aspect of [T] is always in the
 * same order and finite before repeating and another part of [T] is undefined (could be ordered and finite,
 * could be ordered and infinite, could be random).
 *
 * @param T the type of values generated by `this` [SemiOrderedArgsGenerator].
 *
 * @since 2.0.0
 */
interface SemiOrderedArgsGenerator<out T> : SemiOrderedLikeArgsGenerator<T> {
	/**
	 * Maps the values `this` [SemiOrderedArgsGenerator] generates to type [R] with the help of the given [transform] function.
	 *
	 * @param transform The transformation function which takes a [T] and produces an [R].
	 *
	 * @param R the type of values generated by the resulting [SemiOrderedArgsGenerator].
	 *
	 * @return The resulting [SemiOrderedArgsGenerator] which generates values of type [R].
	 *
	 * @since 2.0.0
	 */
	@OptIn(InternalDangerousApi::class)
	override fun <R> map(transform: (T) -> R): SemiOrderedArgsGenerator<R> =
		transformInternal { seq -> seq.map(transform) }
}
