package com.tegonal.variist.generators

/**
 * Represents an [ArgsGenerator] where some part/aspect of [T] is always in the same order and generated a finite number
 * before repeating.
 *
 * The finite number corresponds to its [size] property.
 *
 *
 * @param T the type of values generated by `this` [SemiOrderedLikeArgsGenerator].
 *
 * @since 3.0.0
 */
interface SemiOrderedLikeArgsGenerator<out T> : ArgsGenerator<T> {
	/**
	 * Returns the maximum of values `this` generator is able to generate before some part/aspect of it starts
	 * over again.
	 */
	val size: Int

	/**
	 * Returns the value at the given [offset] requesting to pass the given [seedOffset] to
	 * composed [ArbArgsGenerator]s.
	 */
	fun generateOne(offset: Int, seedOffset: Int = 0): T {
		// we don't use first as it checks hasNext in addition and we know that it has to have one as the
		// Sequence needs to be infinite according to the ArgsGenerator contract
		return generate(offset, seedOffset).iterator().next()
	}

	/**
	 * Returns an infinite [Sequence] of values starting at [offset] -- requesting to pass the given [seedOffset] to
	 * composed [ArbArgsGenerator]s -- and repeating after reaching [size] of values where one part/aspect of
	 * this generator is always the same when generated multiple times.
	 */
	fun generate(offset: Int, seedOffset: Int = 0): Sequence<T>
}
